#!/bin/bash

echo "🔍 Climate Migration App - Debug Backend Issues"
echo "=============================================="
echo ""
echo "📋 Troubleshooting Steps:"
echo ""
echo "1. Check backend logs:"
echo "   pm2 logs climate-app --lines 20"
echo ""
echo "2. Check backend status:"
echo "   pm2 status"
echo ""
echo "3. Test backend API directly:"
echo "   curl -X POST https://climate-migration-app.openeyemedia.net/api/climate/analyze \\"
echo "        -H 'Content-Type: application/json' \\"
echo "        -d '{\"location\": \"London, UK\"}'"
echo ""
echo "4. Check backend health:"
echo "   curl https://climate-migration-app.openeyemedia.net/api/health"
echo ""
echo "🔍 Common Issues & Solutions:"
echo ""
echo "❌ If logs show 'Redis not available':"
echo "   → This is OK, app should work without Redis"
echo ""
echo "❌ If logs show 'ModuleNotFoundError':"
echo "   → Need to install missing Python packages"
echo "   → cd backend && pip install -r requirements.txt"
echo ""
echo "❌ If logs show 'httpx.ConnectError':"
echo "   → External API (Open-Meteo) might be down"
echo "   → App should use fallback data"
echo ""
echo "❌ If logs show 'ImportError: climate_service':"
echo "   → Python path issue, need to restart backend"
echo "   → pm2 restart climate-app"
echo ""
echo "✅ Expected in logs:"
echo "   'Received request for location: London, UK'"
echo "   'Created ClimateDataService, analyzing...'"
echo "   'Analysis completed for London, UK'"
echo ""
echo "📞 Quick Test Command:"
echo "pm2 logs climate-app --lines 5 && curl -X POST https://climate-migration-app.openeyemedia.net/api/climate/analyze -H 'Content-Type: application/json' -d '{\"location\": \"London\"}'"
